blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/alexandroit/stackline-stable-stringify/security/advisories/new
    about: Report a vulnerability privately
